//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT
    {
        public string SeatID { get; set; }
        public string PlaneID { get; set; }
        public string TicketClassID { get; set; }
    
        public virtual PLANE PLANE { get; set; }
        public virtual TICKET_CLASS TICKET_CLASS { get; set; }
    }
}
